"""Replace thin EmDash pages with the rendered content of the live WordPress page.

Many GLC pages are generated by PHP theme templates, so the WXR export has empty bodies. For each
published page whose live text is much longer than its EmDash content, this captures the live
<div id="content"> markup, points uploads at the imported EmDash media, makes internal links relative,
and stores it as a single Portable Text htmlBlock.

Usage: python3 scripts/snapshot-live-pages.py <wxr> <import-result.json> <emdash-pages.json> <out.sql>
  emdash-pages.json: [{"slug": "...", "content": "<portable text json>"}, ...]
"""

import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor

WXR, IMPORT_RESULT, PAGES, OUT = sys.argv[1:5]
LIVE = "https://glcwebsolutions.co.uk"
NS = {"wp": "http://wordpress.org/export/1.2/"}
SIZE_SUFFIX = re.compile(r"-\d+x\d+(?=\.[a-z0-9]+$)", re.I)
UPLOAD_URL = re.compile(r"https?://(?:www\.)?glcwebsolutions\.co\.uk/wp-content/uploads/[^\s\"'()<>,]+", re.I)

url_map = json.load(open(IMPORT_RESULT)).get("urlMap", {})
emdash = {p["slug"]: p["content"] for p in json.load(open(PAGES))}

links = {}
for item in ET.parse(WXR).getroot().iter("item"):
    if item.findtext("wp:post_type", namespaces=NS) == "page" and item.findtext("wp:status", namespaces=NS) == "publish":
        links[item.findtext("wp:post_name", namespaces=NS)] = item.findtext("link")


def words(text):
    return len(re.sub(r"<[^>]+>", " ", text).split())


def emdash_words(content):
    try:
        blocks = json.loads(content or "[]")
    except ValueError:
        return 0
    text = []
    for b in blocks:
        for child in b.get("children", []) or []:
            text.append(child.get("text", ""))
        if b.get("_type") == "htmlBlock":
            text.append(re.sub(r"<[^>]+>", " ", b.get("html", "")))
    return len(" ".join(text).split())


def extract_content(page):
    start = re.search(r'<div\b[^>]*\bid="content"[^>]*>', page)
    if not start:
        return None
    depth, pos = 1, start.end()
    tag = re.compile(r"<(/?)div\b[^>]*>", re.I)
    while depth:
        m = tag.search(page, pos)
        if not m:
            return None
        depth += -1 if m.group(1) else 1
        pos = m.end()
    return page[start.end():m.start()]


def media_url(url):
    clean = url.split("?")[0]
    for candidate in (clean, SIZE_SUFFIX.sub("", clean), clean.replace("https://", "http://")):
        if candidate in url_map:
            return url_map[candidate]
    return url


def clean(html):
    html = re.sub(r"<(script|style|noscript)\b.*?</\1>", "", html, flags=re.S | re.I)
    html = re.sub(r"<!--.*?-->", "", html, flags=re.S)
    html = re.sub(r'\s(?:srcset|sizes)="[^"]*"', "", html)
    html = UPLOAD_URL.sub(lambda m: media_url(m.group(0)), html)
    html = re.sub(r'(href|src|action)="https?://(?:www\.)?glcwebsolutions\.co\.uk(/[^"]*)?"',
                  lambda m: f'{m.group(1)}="{m.group(2) or "/"}"', html)
    return re.sub(r"\n\s*\n+", "\n", html).strip()


def fetch(slug):
    req = urllib.request.Request(links[slug], headers={"User-Agent": "Mozilla/5.0 (GLC EmDash migration)"})
    with urllib.request.urlopen(req, timeout=45) as res:
        return slug, res.read().decode("utf-8", "replace")


targets = [s for s in links if s in emdash]
with ThreadPoolExecutor(8) as pool:
    pages = dict(pool.map(fetch, targets))

statements, report = [], []
for slug in targets:
    body = extract_content(pages[slug])
    if not body:
        report.append((slug, "no #content"))
        continue
    html = clean(body)
    live_w, emdash_w = words(html), emdash_words(emdash[slug])
    if live_w < max(50, emdash_w * 1.5):
        continue
    # D1 caps a statement at 100 KB, so large pages are split at section boundaries and appended
    chunks, current = [], ""
    for part in re.split(r"(?<=</section>)", html):
        if current and len((current + part).encode()) > 60_000:
            chunks.append(current)
            current = ""
        current += part
    chunks.append(current)

    where = f"WHERE slug = '{slug}' AND locale = 'en';"
    page_statements = []
    for i, chunk in enumerate(chunks):
        block = json.dumps({"_type": "htmlBlock", "_key": f"wp-live-snapshot-{i}", "html": chunk}, ensure_ascii=False)
        block_sql = block.replace("'", "''")
        if i == 0:
            page_statements.append(f"UPDATE ec_pages SET content = '[{block_sql}]', "
                                   f"updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') {where}")
        else:
            page_statements.append(f"UPDATE ec_pages SET content = json_insert(content, '$[#]', json('{block_sql}')) {where}")
    too_large = max(len(s.encode()) for s in page_statements)
    if too_large > 95_000:
        report.append((slug, f"too large ({too_large} bytes in one section)"))
        continue
    statements.extend(page_statements)
    report.append((slug, f"snapshot live={live_w} emdash={emdash_w} blocks={len(chunks)}"))

open(OUT, "w").write("\n".join(statements) + "\n")
print(f"pages={len(targets)} snapshots={sum(1 for _, n in report if n.startswith('snapshot'))} statements={len(statements)}")
for slug, note in report:
    if not note.startswith("snapshot"):
        print("  SKIP", slug, note)
unmapped = set(re.findall(r"/wp-content/uploads/[^\s\"'()<>,]+", "\n".join(statements)))
print(f"unmapped upload urls={len(unmapped)}", sorted(unmapped)[:10])
